//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.29 at 11:46:45 AM CEST 
//


package com.thalesgroup.optet.analysis.pmd.jaxb.pmd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="file" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="violation">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="begincolumn" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="beginline" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="endcolumn" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="endline" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="externalinfourl" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                           &lt;attribute name="method" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="package" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="rule" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ruleset" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "file"
})
@XmlRootElement(name = "pmd")
public class Pmd {

    protected List<Pmd.File> file;
    @XmlAttribute(name = "timestamp")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the file property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the file property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Pmd.File }
     * 
     * 
     */
    public List<Pmd.File> getFile() {
        if (file == null) {
            file = new ArrayList<Pmd.File>();
        }
        return this.file;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="violation">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="begincolumn" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="beginline" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="endcolumn" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="endline" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="externalinfourl" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *                 &lt;attribute name="method" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="package" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="rule" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="ruleset" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "violation"
    })
    public static class File {

        @XmlElement(required = true)
        protected Pmd.File.Violation violation;
        @XmlAttribute(name = "name")
        protected String name;

        /**
         * Gets the value of the violation property.
         * 
         * @return
         *     possible object is
         *     {@link Pmd.File.Violation }
         *     
         */
        public Pmd.File.Violation getViolation() {
            return violation;
        }

        /**
         * Sets the value of the violation property.
         * 
         * @param value
         *     allowed object is
         *     {@link Pmd.File.Violation }
         *     
         */
        public void setViolation(Pmd.File.Violation value) {
            this.violation = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="begincolumn" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="beginline" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="endcolumn" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="endline" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="externalinfourl" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *       &lt;attribute name="method" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="package" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="rule" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="ruleset" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Violation {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "begincolumn")
            protected Byte begincolumn;
            @XmlAttribute(name = "beginline")
            protected Byte beginline;
            @XmlAttribute(name = "class")
            protected String clazz;
            @XmlAttribute(name = "endcolumn")
            protected Byte endcolumn;
            @XmlAttribute(name = "endline")
            protected Byte endline;
            @XmlAttribute(name = "externalinfourl")
            @XmlSchemaType(name = "anyURI")
            protected String externalinfourl;
            @XmlAttribute(name = "method")
            protected String method;
            @XmlAttribute(name = "package")
            protected String _package;
            @XmlAttribute(name = "priority")
            protected Byte priority;
            @XmlAttribute(name = "rule")
            protected String rule;
            @XmlAttribute(name = "ruleset")
            protected String ruleset;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the begincolumn property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getBegincolumn() {
                return begincolumn;
            }

            /**
             * Sets the value of the begincolumn property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setBegincolumn(Byte value) {
                this.begincolumn = value;
            }

            /**
             * Gets the value of the beginline property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getBeginline() {
                return beginline;
            }

            /**
             * Sets the value of the beginline property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setBeginline(Byte value) {
                this.beginline = value;
            }

            /**
             * Gets the value of the clazz property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClazz() {
                return clazz;
            }

            /**
             * Sets the value of the clazz property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClazz(String value) {
                this.clazz = value;
            }

            /**
             * Gets the value of the endcolumn property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getEndcolumn() {
                return endcolumn;
            }

            /**
             * Sets the value of the endcolumn property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setEndcolumn(Byte value) {
                this.endcolumn = value;
            }

            /**
             * Gets the value of the endline property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getEndline() {
                return endline;
            }

            /**
             * Sets the value of the endline property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setEndline(Byte value) {
                this.endline = value;
            }

            /**
             * Gets the value of the externalinfourl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExternalinfourl() {
                return externalinfourl;
            }

            /**
             * Sets the value of the externalinfourl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExternalinfourl(String value) {
                this.externalinfourl = value;
            }

            /**
             * Gets the value of the method property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMethod() {
                return method;
            }

            /**
             * Sets the value of the method property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMethod(String value) {
                this.method = value;
            }

            /**
             * Gets the value of the package property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPackage() {
                return _package;
            }

            /**
             * Sets the value of the package property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPackage(String value) {
                this._package = value;
            }

            /**
             * Gets the value of the priority property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getPriority() {
                return priority;
            }

            /**
             * Sets the value of the priority property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setPriority(Byte value) {
                this.priority = value;
            }

            /**
             * Gets the value of the rule property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRule() {
                return rule;
            }

            /**
             * Sets the value of the rule property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRule(String value) {
                this.rule = value;
            }

            /**
             * Gets the value of the ruleset property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRuleset() {
                return ruleset;
            }

            /**
             * Sets the value of the ruleset property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRuleset(String value) {
                this.ruleset = value;
            }

        }

    }

}
